-- when spring.datasource.initialize: true

CREATE SEQUENCE SOURCE_ID_SEQ;
CREATE TABLE SOURCE
(
  OID        BIGINT DEFAULT (NEXT VALUE FOR SOURCE_ID_SEQ) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  KIND       VARCHAR(31)                                                              NOT NULL,
  NAME       VARCHAR(255),
  EMAIL      VARCHAR(255),
  PHONE      VARCHAR(255),
  DIRECTIONS VARCHAR(255),
  URL        VARCHAR(255)
);

CREATE SEQUENCE ITEM_ID_SEQ;
CREATE TABLE ITEM
(
  OID        BIGINT DEFAULT (NEXT VALUE FOR ITEM_ID_SEQ) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  IMAGE      BLOB,
  NAME       VARCHAR(255),
  RECEIVED   TIMESTAMP,
  PRICE      VARCHAR(255),
  REFERENCE  VARCHAR(255),
  UNIT       VARCHAR(255),
  SOURCE_OID BIGINT,
  CONSTRAINT FKS6U7F2DO1GRMI4MLFO1IE9IA0 FOREIGN KEY (SOURCE_OID) REFERENCES SOURCE (OID)
);

CREATE SEQUENCE VESSEL_ID_SEQ;
CREATE TABLE VESSEL
(
  OID    BIGINT DEFAULT (NEXT VALUE FOR VESSEL_ID_SEQ) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  VOLUME VARCHAR(255),
  CONSTRAINT FKE7DSWMLB7X75VBW49NLYIKDET FOREIGN KEY (OID) REFERENCES ITEM (OID)
);

CREATE SEQUENCE RECIPE_ID_SEQ;
CREATE TABLE RECIPE
(
  OID          BIGINT DEFAULT (NEXT VALUE FOR RECIPE_ID_SEQ) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  IMAGE        BLOB,
  NAME         VARCHAR(255),
  RECEIVED     TIMESTAMP,
  INSTRUCTIONS VARCHAR(255),
  VOLUME       VARCHAR(255),
  SOURCE_OID   BIGINT,
  CONSTRAINT FKR2RLY8MPLYGTEEOB2NYLI5UIP FOREIGN KEY (SOURCE_OID) REFERENCES SOURCE (OID)
);
CREATE TABLE RECIPE_INGREDIENTS
(
  RECIPE_OID   BIGINT NOT NULL,
  ITEM_OID     BIGINT,
  AMOUNT       VARCHAR(255),
  INSTRUCTIONS VARCHAR(255),
  CONSTRAINT FK8CYNDMOT64HGR3QG78A6I9F0T FOREIGN KEY (RECIPE_OID) REFERENCES RECIPE (OID),
  CONSTRAINT FKBATQ6L559SKHTQ5PLQG44136S FOREIGN KEY (ITEM_OID) REFERENCES ITEM (OID)
);

CREATE SEQUENCE MOTHER_ID_SEQ;
CREATE TABLE MOTHER
(
  OID        BIGINT DEFAULT (NEXT VALUE FOR MOTHER_ID_SEQ) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  IMAGE      BLOB,
  NAME       VARCHAR(255),
  RECEIVED   TIMESTAMP,
  SOURCE_OID BIGINT,
  MOTHER_OID BIGINT,
  CONSTRAINT FKCMGHHX1VGGF669W3N9L2WP72I FOREIGN KEY (SOURCE_OID) REFERENCES SOURCE (OID),
  CONSTRAINT FK4UUTVSMQERE0FEES7MYS99SQ1 FOREIGN KEY (MOTHER_OID) REFERENCES MOTHER (OID)
);

CREATE SEQUENCE FERMENT_ID_SEQ;
CREATE TABLE FERMENT
(
  OID        BIGINT DEFAULT (NEXT VALUE FOR FERMENT_ID_SEQ) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  IMAGE      BLOB,
  NAME       VARCHAR(255),
  PROCESSING VARCHAR(255),
  START      TIMESTAMP,
  STOP       TIMESTAMP,
  VOLUME     VARCHAR(255),
  MOTHER_OID BIGINT,
  RECIPE_OID BIGINT,
  VESSEL_OID BIGINT,
  CONSTRAINT FKTBLE39W0XWWDLWGRIUX2LBTTX FOREIGN KEY (MOTHER_OID) REFERENCES MOTHER (OID),
  CONSTRAINT FK2UPTC8ANSTI2H7TEDRV39GB0H FOREIGN KEY (RECIPE_OID) REFERENCES RECIPE (OID),
  CONSTRAINT FK3UGAOJOHB1658DKU8TG672Y9O FOREIGN KEY (VESSEL_OID) REFERENCES VESSEL (OID)
);

CREATE SEQUENCE SAMPLE_ID_SEQ;
CREATE TABLE SAMPLE
(
  OID         BIGINT DEFAULT (NEXT VALUE FOR SAMPLE_ID_SEQ) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  IMAGE       BLOB,
  MEASUREMENT VARCHAR(255),
  TAKEN       TIMESTAMP,
  FERMENT_OID BIGINT,
  CONSTRAINT FKDJYK75BXJIIQ5I0NPH4THOMHM FOREIGN KEY (FERMENT_OID) REFERENCES FERMENT (OID)
);
